refacto workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,61 +19,62 @@ jobs:
         id: get-version
         run: |
           HTTP_STATUS=$(curl -s -o response.json -w "%{http_code}" https://api.github.com/repos/caddyserver/caddy/releases/latest)
+
           if [ "$HTTP_STATUS" -ne 200 ]; then
             echo "Failed to fetch API response. HTTP Status: $HTTP_STATUS"
-            exit 1
+            echo "skip=true" >> $GITHUB_OUTPUT
+          else
+            echo "skip=false" >> $GITHUB_OUTPUT
+
+            LATEST_VERSION=$(jq -r '.tag_name' response.json)
+            if [ -z "$LATEST_VERSION" ]; then
+              echo "Failed to parse the latest version from the API response."
+              exit 1
+            fi
+
+            echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
+            echo "Latest Caddy version is $LATEST_VERSION"
           fi
-          LATEST_VERSION=$(jq -r '.tag_name' response.json)
-          if [ -z "$LATEST_VERSION" ]; then
-            echo "Failed to parse the latest version from the API response."
-            exit 1
-          fi
-          echo "latest_version=$LATEST_VERSION" >> $GITHUB_OUTPUT
-          echo "Latest Caddy version is $LATEST_VERSION"
 
       - name: Check if Release Exists
         id: check-release
         run: |
-          RESPONSE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get-version.outputs.latest_version }})
-          echo "API Response: $RESPONSE"
-          if echo "$RESPONSE" | jq -e '.id' > /dev/null; then
-            echo "Release exists."
+          if [ "${{ steps.get-version.outputs.skip }}" == "true" ]; then
             echo "skip=true" >> $GITHUB_OUTPUT
           else
-            echo "skip=false" >> $GITHUB_OUTPUT
+            RESPONSE=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.get-version.outputs.latest_version }})
+            echo "API Response: $RESPONSE"
+            if echo "$RESPONSE" | jq -e '.id' > /dev/null; then
+              echo "Release exists."
+              echo "skip=true" >> $GITHUB_OUTPUT
+              echo "Release already exists. Skipping build."
+              exit 0
+            else
+              echo "skip=false" >> $GITHUB_OUTPUT
+            fi
           fi
 
-      - name: Skip Job if Release Exists
-        if: steps.check-release.outputs.skip == 'true'
-        run: echo "Release already exists. Skipping build."
-
       - name: Checkout Repository
-        if: steps.check-release.outputs.skip == 'false'
         uses: actions/checkout@v4
 
       - name: Set up Go
-        if: steps.check-release.outputs.skip == 'false'
         uses: actions/setup-go@v5
         with:
           go-version: 'stable'
 
       - name: Install xcaddy
-        if: steps.check-release.outputs.skip == 'false'
         run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
 
       - name: Build Caddy
-        if: steps.check-release.outputs.skip == 'false'
         run: |
           GOOS=linux GOARCH=${{ matrix.arch }} xcaddy build \
             --output caddy-${{ matrix.arch }} \
             --with github.com/lucaslorentz/caddy-docker-proxy/v2
       
       - name: Generate SHA256
-        if: steps.check-release.outputs.skip == 'false'
         run: sha256sum caddy-${{ matrix.arch }} > caddy-${{ matrix.arch }}.sha256
 
       - name: Upload Artifact
-        if: steps.check-release.outputs.skip == 'false'
         uses: actions/upload-artifact@v4
         with:
           name: caddy-${{ matrix.arch }}
@@ -87,22 +88,19 @@ jobs:
     steps:
       - name: Skip Job if Release Exists
         if: needs.build.outputs.skip == 'true'
-        run: echo "Release already exists."
+        run: echo "Release already exists." && exit 0
 
       - name: Download amd64 Binary
-        if: needs.build.outputs.skip == 'false'
         uses: actions/download-artifact@v4
         with:
           name: caddy-amd64
 
       - name: Download arm64 Binary
-        if: needs.build.outputs.skip == 'false'
         uses: actions/download-artifact@v4
         with:
           name: caddy-arm64
 
       - name: Create Release
-        if: needs.build.outputs.skip == 'false'
         uses: ncipollo/release-action@v1
         with:
           artifacts: "caddy-*"
